"use client";
import { useState } from "react";
type Grid=number[][]; type Mode="diagonal"|"anti-diagonal"|"one-of-each";
const A=0b111111111, empty=()=>Array.from({length:9},()=>Array(9).fill(0));
const bits=(n:number)=>n.toString(2).replaceAll("0","").length;
const shuffle=(a:number[])=>{const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r};
const anti=[[1,6,5,2,3,8,7,9,4],[4,2,7,6,1,9,3,5,8],[8,9,3,4,5,7,2,1,6],[5,3,9,1,7,4,6,8,2],[7,4,8,9,2,6,5,3,1],[6,1,2,5,8,3,4,7,9],[3,7,4,8,9,2,1,6,5],[9,5,6,3,4,1,8,2,7],[2,8,1,7,6,5,9,4,3]];
function make(mode:Mode):Grid{
 if(mode==="anti-diagonal"){const p=shuffle([1,2,3,4,5,6,7,8,9]);return anti.map(r=>r.map(x=>p[x-1]))}
 const g=empty(),R=Array(9).fill(0),C=Array(9).fill(0),H=Array(9).fill(0),D=[0,0];
 const put=(r:number,c:number,n:number)=>{const b=1<<(n-1),h=(r/3|0)*3+(c/3|0);g[r][c]=n;R[r]|=b;C[c]|=b;H[h]|=b;if(r===c)D[0]|=b;if(r+c===8)D[1]|=b};
 const take=(r:number,c:number,n:number)=>{const b=1<<(n-1),h=(r/3|0)*3+(c/3|0);g[r][c]=0;R[r]^=b;C[c]^=b;H[h]^=b;if(r===c)D[0]^=b;if(r+c===8)D[1]^=b};
 if(mode==="one-of-each"){[4,5,2,4,2,5,4,5,2].forEach((n,r)=>put(r,8-r,n))}
 const solve=():boolean=>{let br=-1,bc=-1,opts=0,few=10;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!g[r][c]){let u=R[r]|C[c]|H[(r/3|0)*3+(c/3|0)];if(mode!=="one-of-each"&&r===c)u|=D[0];if(mode==="diagonal"&&r+c===8)u|=D[1];const o=A&~u,k=bits(o);if(k<few){br=r;bc=c;opts=o;few=k}}if(br<0)return true;if(!few)return false;for(const n of shuffle([1,2,3,4,5,6,7,8,9]).filter(n=>opts&(1<<(n-1)))){put(br,bc,n);if(solve())return true;take(br,bc,n)}return false};
 solve();const map=shuffle([1,2,3,4,5,6,7,8,9]);const result=g.map(r=>r.map(n=>map[n-1]));return mode==="one-of-each"&&Math.random()<.5?result[0].map((_,c)=>result.map(r=>r[c])):result;
}
function count(start:Grid){const g=start.map(r=>[...r]),R=Array(9).fill(0),C=Array(9).fill(0),H=Array(9).fill(0),D=[0,0];for(let r=0;r<9;r++)for(let c=0;c<9;c++){const n=g[r][c];if(n){const b=1<<(n-1),h=(r/3|0)*3+(c/3|0);R[r]|=b;C[c]|=b;H[h]|=b;if(r===c)D[0]|=b;if(r+c===8)D[1]|=b}}let total=0;const go=():void=>{if(total>1)return;let br=-1,bc=-1,o=0,few=10;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!g[r][c]){let u=R[r]|C[c]|H[(r/3|0)*3+(c/3|0)];if(r===c)u|=D[0];if(r+c===8)u|=D[1];const x=A&~u,k=bits(x);if(k<few){br=r;bc=c;o=x;few=k}}if(br<0){total++;return}for(let n=1;n<=9;n++)if(o&(1<<(n-1))){const b=1<<(n-1),h=(br/3|0)*3+(bc/3|0);g[br][bc]=n;R[br]|=b;C[bc]|=b;H[h]|=b;if(br===bc)D[0]|=b;if(br+bc===8)D[1]|=b;go();g[br][bc]=0;R[br]^=b;C[bc]^=b;H[h]^=b;if(br===bc)D[0]^=b;if(br+bc===8)D[1]^=b}};go();return total}
function dig(){const solution=make("diagonal"),puzzle=solution.map(r=>[...r]);for(const x of shuffle(Array.from({length:81},(_,i)=>i))){const r=x/9|0,c=x%9,n=puzzle[r][c];puzzle[r][c]=0;if(count(puzzle)!==1)puzzle[r][c]=n}return {solution,puzzle}}
export default function Home(){const [mode,setMode]=useState<Mode>("diagonal"),[grid,setGrid]=useState<Grid>(empty),[solution,setSolution]=useState<Grid|null>(null),[time,setTime]=useState<number|null>(null);const choose=(m:Mode)=>{setMode(m);setGrid(empty());setSolution(null);setTime(null)};const generate=()=>{const t=performance.now();if(mode==="diagonal"){const d=dig();setGrid(d.puzzle);setSolution(d.solution)}else{setGrid(make(mode));setSolution(null)}setTime(performance.now()-t)};const desc={diagonal:"Normal Sudoku rules apply. Digits along the indicated diagonals cannot repeat.","anti-diagonal":"Normal Sudoku rules apply. Exactly three distinct numbers appear along each marked diagonal.","one-of-each":"Normal Sudoku rules apply. Digits along one diagonal cannot repeat, while digits along the other diagonal each appear three times. It is up to the solver to determine which diagonal follows which rule."};const cells=(g:Grid,complete=false)=>g.flatMap((r,i)=>r.map((v,j)=><div className={complete?(grid[i][j]?"cell given":"cell solved"):"cell"} key={i+"-"+j}>{v||""}</div>));return <main className="page"><h1>Diagonal or not</h1><div className="mode-picker"><button className={mode==="diagonal"?"active":""} onClick={()=>choose("diagonal")}>Diagonal</button><button className={mode==="anti-diagonal"?"active":""} onClick={()=>choose("anti-diagonal")}>Anti-diagonal</button><button className={mode==="one-of-each"?"active":""} onClick={()=>choose("one-of-each")}>One of each</button></div><p className="rule-description">{desc[mode]}</p><div className="grid-frame"><svg className="diagonal-guides" viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="0" y1="0" x2="50" y2="50"/><line x1="100" y1="100" x2="50" y2="50"/><line x1="100" y1="0" x2="50" y2="50"/><line x1="0" y1="100" x2="50" y2="50"/></svg><div className="grid">{cells(grid)}</div></div><button className="generate-button" onClick={generate}>Generate a grid</button>{mode==="diagonal"&&solution&&<section className="dig-results"><p>{grid.flat().filter(Boolean).length} givens · {(time??0).toFixed(0)} ms</p><h2>Completed grid</h2><div className="grid solution-grid">{cells(solution,true)}</div></section>}</main>}
